apiVersion: v1
kind: Pod
metadata:
  name: myapp-pods
  # labels are comments/tags
  labels:
     app: myapps
     type: front-end
spec:
   containers:
     - name: nginx-controller
       image: nginx
     - name: busybox
       image: busybox
